In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch

In [17]:
from Core.Dataset import PoseModelDataset
from Configs.Configs import PoseTransformersConfig, PoseMLPConfig
from Core.Utils import DDPM, diffusion_noise_schedule

In [27]:
config_mlp = PoseMLPConfig()
config_transformer = PoseTransformersConfig()

In [28]:
dataset = PoseModelDataset(config_transformer)

Number of sequences 14096


In [43]:
test = DDPM('pose_mlp')

In [45]:
test.train(config_mlp, 2)

****** Training Initiated ******
Run number: 2
Config:
    inp_dim = 144
    out_dim = 50
    data_dir = './Data/PoseData'
    smpl_model_dir = './SupportingFiles/SMPLModel/smpl/models/basicmodel_m_lbs_10_207_0_v1.1.0.pkl'
    save_dir = './Models/PoseMLP'
    subset = 'full'
    wt_norm_ind = False
    act_lyr = 'batch'
    act_fn = 'gelu'
    batch_size = 1024
    n_workers = 4
    lr = 0.0001
    wt_decay = 0.001
    save_bw_ep = True
    n_epochs = 500
    n_resnets = 3
    n_hid_dim = 128
    drop_prob = 0.1
    n_time = 500
    beta_range = (0.0001, 0.02)
    n_epochs_bw_saves = 50
Number of sequences 14096


  0%|          | 0/500 [00:00<?, ?it/s]

0 1.148564338684082
1 2.2937159538269043
2 3.4325404167175293
3 4.567712783813477


Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f093b393160>
Traceback (most recent call last):
  File "/home/darve/apoorv1/.conda/envs/diff/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1510, in __del__
    self._shutdown_workers()
  File "/home/darve/apoorv1/.conda/envs/diff/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1493, in _shutdown_workers
    if w.is_alive():
  File "/home/darve/apoorv1/.conda/envs/diff/lib/python3.9/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f093b393160>
Traceback (most recent call last):
  File "/home/darve/apoorv1/.conda/envs/diff/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1510, in __del__
    self._shutdown_workers()
  File "/home/darve/apoorv1/.conda/envs/diff/

KeyboardInterrupt: 

In [23]:
data.shape

torch.Size([16, 8, 144])

In [19]:
[alpha, beta, sqrt_alpha_bar,
         sqrt_om_alpha_bar]=diffusion_noise_schedule(config_transformer.n_time, config_transformer.beta_range)

In [20]:
inp_t_ind=torch.randint(0, config_transformer.n_time, (16, 1))


In [ ]:
inp_x = (data_x*sqrt_alpha_bar[inp_t_ind] + inp_noise*sqrt_om_alpha_bar[inp_t_ind]).to(device)

In [21]:
sqrt_alpha_bar[inp_t_ind].shape

torch.Size([16, 1])

In [24]:
data_x = data.view(-1, data.shape[-1])

In [25]:
data_x.shape

torch.Size([128, 144])

In [26]:
16*8

128

In [47]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [48]:
print(device)

cpu


In [1]:
import torch
print(torch.__version__)
print(torch.version.cuda)
print(torch.backends.cudnn.version())

2.3.1+cu118
11.8
8700


In [2]:
temp = torch.randn(3, 3, 2)

In [4]:
temp[0, :, :]

tensor([[-1.2617, -0.4084],
        [-0.7194,  1.7390],
        [ 0.4131,  1.1487]])

In [6]:
temp[1, :, :]

tensor([[-0.8692,  0.7863],
        [-2.2450, -1.0492],
        [-0.7934, -1.8614]])

In [7]:
temp[2, :, :]

tensor([[-0.1673,  0.1973],
        [-1.7958,  0.2298],
        [ 0.8069, -0.0644]])

In [9]:
temp_2 = temp.view(-1, temp.shape[-1])